# Generated by Django 4.1.6 on 2023-02-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_auth', '0006_remove_question_pub_date_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
