# Generated by Django 4.1.6 on 2023-02-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_auth', '0009_remove_question_answer_user_answer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
