# Generated by Django 4.1.6 on 2023-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_auth', '0011_user_qwiz_alter_user_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='answer',
            new_name='answer1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qwiz',
        ),
        migrations.AddField(
            model_name='user',
            name='answer2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
