# Generated by Django 4.1.6 on 2023-02-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_auth', '0012_rename_answer_user_answer1_remove_user_qwiz_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
