# Generated by Django 4.1.6 on 2023-02-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_auth', '0015_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(related_name='questions', to='acc_auth.choice'),
        ),
    ]
